### Prueba del microsevicio
GET http://127.0.0.1:8000/
Content-Type: text/html

# ---------- CONSULTA GENERAL (INDEX-GET) --------------

### TABLA INGRESOS
GET http://127.0.0.1:8000/api/ingresos
Content-Type: application/json
### TABLA HORARIOS
GET http://127.0.0.1:8000/api/horarios_salas
Content-Type: application/json
### TABLA PROGRAMAS
GET http://127.0.0.1:8000/api/programas
Content-Type: application/json
### TABLA RESPONSABLES
GET http://127.0.0.1:8000/api/responsables
Content-Type: application/json
### TABLA SALAS
GET http://127.0.0.1:8000/api/salas
Content-Type: application/json


# ---------- CONSULTA ESPECIFICA (SHOW-GET) -------------- 

### TABLA INGRESOS
GET http://127.0.0.1:8000/api/ingresos/1
Content-Type: application/json
### TABLA HORARIOS
GET http://127.0.0.1:8000/api/horarios_salas/1
Content-Type: application/json
### TABLA PROGRAMAS
GET http://127.0.0.1:8000/api/programas/1
Content-Type: application/json
### TABLA RESPONSABLES
GET http://127.0.0.1:8000/api/responsables/1
Content-Type: application/json
### TABLA SALAS
GET http://127.0.0.1:8000/api/salas/1
Content-Type: application/json


# ---------- REGISTRAR (STORE-POST) --------------

### TABLA INGRESOS
POST http://127.0.0.1:8000/api/ingresos
Content-Type: application/json

{
   "codigoEstudiante": "55823012",
   "nombreEstudiante": "Dankel Daraz",
   "idPrograma":"3",
   "fechaIngreso":"2024/06/05",
   "horaIngreso":"12:35",
   "horaSalida":null,
   "idResponsable":"1",
   "idSala":"1"
}

### TABLA HORARIOS
POST http://127.0.0.1:8000/api/horarios_salas
Content-Type: application/json

{
   "dia":"Martes",
   "materia":"Dibujo",
   "horaInicio":"14:00",
   "horaFin":"18:20",
   "idPrograma ":"1",
   "idSala ":"1"
}


# ---------- ACTUALIZAR (UPDATE-PUT) --------------

### TABLA INGRESOS
PUT http://127.0.0.1:8000/api/ingresos/6
Content-Type: application/json

{
   "fechaIngreso":"2024/06/06"
}

### TABLA HORARIO SALAS
PUT http://127.0.0.1:8000/api/horarios_salas/4
Content-Type: application/json

{
   "dia":"Martes",
   "materia":"Dibujo",
   "horaInicio":"14:59",
   "horaFin":"18:20",
   "idPrograma ":"1",
   "idSala ":"1"
}







