### Prueba del microsevicio
GET http://127.0.0.1:8000/
Content-Type: text/html

# ---------- CONSULTA GENERAL (INDEX-GET) --------------

### TABLA INGRESOS
GET http://127.0.0.1:8000/api/ingresos
Content-Type: application/json
### TABLA HORARIOS
GET http://127.0.0.1:8000/api/horarios
Content-Type: application/json
### TABLA PROGRAMAS
GET http://127.0.0.1:8000/api/programas
Content-Type: application/json


# ---------- CONSULTA ESPECIFICA (SHOW-GET) --------------

### TABLA INGRESOS
GET http://127.0.0.1:8000/api/ingresos/13
Content-Type: application/json
### TABLA HORARIOS
GET http://127.0.0.1:8000/api/horarios/13
Content-Type: application/json


# ---------- REGISTRAR (STORE-POST) --------------

### TABLA INGRESOS
POST http://127.0.0.1:8000/api/ingresos
Content-Type: application/json

{
   "codigoEstudiante": "587906778",
   "nombreEstudiante": "Anita la la tina",
   "idPrograma":"1",
   "fechaIngreso":"2024/05/29",
   "horaIngreso":"14:00",

   "idResponsable":"2",
   "idSala":"4"
}

### TABLA HORARIOS
POST http://127.0.0.1:8000/api/horarios
Content-Type: application/json

{
   "dia": "Sábado",
   "materia": "Programación",
   "horaInicio":"10:00am",
   "horaFin":"12:00pm",
   "idPrograma":"1",
   "idSala":"4"
}

# ---------- ACTUALIZAR (UPDATE-PUT) --------------

### TABLA INGRESOS
PUT http://127.0.0.1:8000/api/ingresos/13
Content-Type: application/json

{
   "codigoEstudiante": "5566778899",
   "nombreEstudiante": "Anita latina",
}






